seed: 42

n_timesteps: !!float 2e6
policy: 'MlpPolicy'
n_steps: 24
batch_size: 8192
gae_lambda: 0.95
gamma: 0.99
n_epochs: 10
ent_coef: 0.01
learning_rate: !!float 3e-4
clip_range: !!float 0.2
policy_kwargs:
  activation_fn: nn.ELU
  net_arch: [128, 128, 64]
  squash_output: False
vf_coef: 1.0
max_grad_norm: 1.0
device: "cuda:0"
